package views;

import controller.ControllerUser;
//import java.sql.Connection;
//import javax.swing.table.DefaultTableModel;
//import database.DBConnection;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
//import java.sql.ResultSetMetaData;
import model.EntityUser;

public class ViewNesti extends javax.swing.JFrame {

    private EntityUser user = new EntityUser();

    public EntityUser getUser() {
        return user;
    }

    public void setUser(EntityUser user) {
        this.user = user;
    }
    

    /**
     * Creates new form ViewNesti
     * @param user
     */
//    public ViewNesti() {
//        initComponents();
//    }

    public ViewNesti(EntityUser user) {
        this.user = user;
        System.out.println(this.user.getId_role());
        initComponents();
        setLocationRelativeTo(null);

        lbl_name_home.setText(user.getUsername());
        lbl_role_home.setText(user.getDescription_role());

        //----ROLE PRIVILEGES
//        if (user.getId_role() == 1) {
//
//        } else if (user.getId_role() == 2) {
//            System.out.println("tessst");
//            JPanel_suppliers.setVisible(false);
//            JPanel_users.setVisible(false);
//
//        }
        
        if ("SUPER ADMIN".equals(user.getDescription_role())) {

        } else if ("ADMIN".equals(user.getDescription_role())) {
            JPanel_suppliers.setVisible(false);
            JPanel_users.setVisible(false);

        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nesti = new javax.swing.JTabbedPane();
        JPanel_home = new javax.swing.JPanel();
        lbl_role_home = new javax.swing.JLabel();
        lbl_name_home = new javax.swing.JLabel();
        lbl_title_home = new javax.swing.JLabel();
        JPanel_Nesti = new javax.swing.JPanel();
        JPanel_articles = new javax.swing.JPanel();
        JPanel_suppliers = new javax.swing.JPanel();
        JPanel_users = new javax.swing.JPanel();
        lblTtitle = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        lbl_passwordConfirm = new javax.swing.JLabel();
        lbl_role = new javax.swing.JLabel();
        input_name = new javax.swing.JTextField();
        input_username = new javax.swing.JTextField();
        input_password = new javax.swing.JPasswordField();
        input_confirmPassword = new javax.swing.JPasswordField();
        input_id = new javax.swing.JTextField();
        input_search = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        combo_role = new javax.swing.JComboBox<>();
        btn_modify = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        btn_search_user = new javax.swing.JButton();
        btn_table1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_user = new javax.swing.JTable();
        table = new javax.swing.JButton();
        input_searchT = new javax.swing.JTextField();
        lbl_name_search = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nesti.setBackground(new java.awt.Color(255, 255, 255));
        nesti.setForeground(new java.awt.Color(0, 204, 204));

        JPanel_home.setBackground(new java.awt.Color(153, 153, 153));

        lbl_title_home.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lbl_title_home.setForeground(new java.awt.Color(0, 204, 204));
        lbl_title_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title_home.setText("Welcome to the Nesti Gestion application");

        javax.swing.GroupLayout JPanel_homeLayout = new javax.swing.GroupLayout(JPanel_home);
        JPanel_home.setLayout(JPanel_homeLayout);
        JPanel_homeLayout.setHorizontalGroup(
            JPanel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_homeLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(JPanel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_name_home, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_role_home, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_homeLayout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(lbl_title_home, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );
        JPanel_homeLayout.setVerticalGroup(
            JPanel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_homeLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lbl_title_home, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_name_home, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_role_home, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        nesti.addTab("Home", JPanel_home);

        javax.swing.GroupLayout JPanel_NestiLayout = new javax.swing.GroupLayout(JPanel_Nesti);
        JPanel_Nesti.setLayout(JPanel_NestiLayout);
        JPanel_NestiLayout.setHorizontalGroup(
            JPanel_NestiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1021, Short.MAX_VALUE)
        );
        JPanel_NestiLayout.setVerticalGroup(
            JPanel_NestiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        nesti.addTab("Nesti", JPanel_Nesti);

        javax.swing.GroupLayout JPanel_articlesLayout = new javax.swing.GroupLayout(JPanel_articles);
        JPanel_articles.setLayout(JPanel_articlesLayout);
        JPanel_articlesLayout.setHorizontalGroup(
            JPanel_articlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1021, Short.MAX_VALUE)
        );
        JPanel_articlesLayout.setVerticalGroup(
            JPanel_articlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        nesti.addTab("Articles", JPanel_articles);

        javax.swing.GroupLayout JPanel_suppliersLayout = new javax.swing.GroupLayout(JPanel_suppliers);
        JPanel_suppliers.setLayout(JPanel_suppliersLayout);
        JPanel_suppliersLayout.setHorizontalGroup(
            JPanel_suppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1021, Short.MAX_VALUE)
        );
        JPanel_suppliersLayout.setVerticalGroup(
            JPanel_suppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        nesti.addTab("Suppliers", JPanel_suppliers);

        JPanel_users.setBackground(new java.awt.Color(255, 255, 255));

        lblTtitle.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTtitle.setForeground(new java.awt.Color(0, 204, 204));
        lblTtitle.setText("Register User");

        lbl_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(0, 204, 204));
        lbl_name.setText("Name: ");

        lbl_username.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(0, 204, 204));
        lbl_username.setText("Username:");

        lbl_password.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(0, 204, 204));
        lbl_password.setText("Password:");

        lbl_passwordConfirm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_passwordConfirm.setForeground(new java.awt.Color(0, 204, 204));
        lbl_passwordConfirm.setText("Confirm Password:");

        lbl_role.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_role.setForeground(new java.awt.Color(0, 204, 204));
        lbl_role.setText("Role: ");

        input_password.setText("jPasswordField1");

        input_confirmPassword.setText("jPasswordField1");

        btn_register.setBackground(new java.awt.Color(0, 0, 0));
        btn_register.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btn_register.setForeground(new java.awt.Color(0, 204, 204));
        btn_register.setText("Register");

        btn_modify.setBackground(new java.awt.Color(0, 0, 0));
        btn_modify.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btn_modify.setForeground(new java.awt.Color(0, 204, 204));
        btn_modify.setText("Update");

        btn_remove.setBackground(new java.awt.Color(0, 0, 0));
        btn_remove.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btn_remove.setForeground(new java.awt.Color(0, 204, 204));
        btn_remove.setText("Delete");

        btn_search_user.setBackground(new java.awt.Color(0, 0, 0));
        btn_search_user.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_search_user.setForeground(new java.awt.Color(0, 153, 153));
        btn_search_user.setText("Search");

        btn_table1.setText("CargarTabla2");

        table_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "USERNAME", "PASSWORD", "ROLE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_user);

        table.setText("ok");
        table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableActionPerformed(evt);
            }
        });

        lbl_name_search.setText("name:");

        javax.swing.GroupLayout JPanel_usersLayout = new javax.swing.GroupLayout(JPanel_users);
        JPanel_users.setLayout(JPanel_usersLayout);
        JPanel_usersLayout.setHorizontalGroup(
            JPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_usersLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(JPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_password, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_username, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_name, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblTtitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(lbl_password, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_username, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_passwordConfirm, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_name, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_role, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(JPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_register, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addComponent(combo_role, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(input_confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(JPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel_usersLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btn_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(JPanel_usersLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanel_usersLayout.createSequentialGroup()
                                .addComponent(btn_table1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(table)
                                .addGap(35, 35, 35)
                                .addComponent(lbl_name_search)
                                .addGap(28, 28, 28)
                                .addComponent(input_searchT, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(input_search, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_search_user))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(59, Short.MAX_VALUE))))
            .addGroup(JPanel_usersLayout.createSequentialGroup()
                .addComponent(input_id, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JPanel_usersLayout.setVerticalGroup(
            JPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_usersLayout.createSequentialGroup()
                .addComponent(input_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(JPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_table1)
                        .addComponent(table))
                    .addGroup(JPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_search_user)
                        .addComponent(input_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(input_searchT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_name_search)))
                .addGap(18, 18, 18)
                .addGroup(JPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel_usersLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(JPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_remove))
                        .addGap(17, 17, 17))
                    .addGroup(JPanel_usersLayout.createSequentialGroup()
                        .addComponent(lbl_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_name, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_username)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_username, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_password)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_password, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_passwordConfirm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_role)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        nesti.addTab("Users", JPanel_users);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nesti)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nesti)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableActionPerformed
        ControllerUser  user = new ControllerUser();
        user.btn_ok(table_user, input_searchT);
    }//GEN-LAST:event_tableActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel_Nesti;
    private javax.swing.JPanel JPanel_articles;
    private javax.swing.JPanel JPanel_home;
    private javax.swing.JPanel JPanel_suppliers;
    private javax.swing.JPanel JPanel_users;
    public javax.swing.JButton btn_modify;
    public javax.swing.JButton btn_register;
    public javax.swing.JButton btn_remove;
    public javax.swing.JButton btn_search_user;
    public javax.swing.JButton btn_table1;
    public javax.swing.JComboBox<String> combo_role;
    public javax.swing.JPasswordField input_confirmPassword;
    public javax.swing.JTextField input_id;
    public javax.swing.JTextField input_name;
    public javax.swing.JPasswordField input_password;
    public javax.swing.JTextField input_search;
    public javax.swing.JTextField input_searchT;
    public javax.swing.JTextField input_username;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTtitle;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_name_home;
    private javax.swing.JLabel lbl_name_search;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_passwordConfirm;
    private javax.swing.JLabel lbl_role;
    private javax.swing.JLabel lbl_role_home;
    private javax.swing.JLabel lbl_title_home;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JTabbedPane nesti;
    private javax.swing.JButton table;
    public javax.swing.JTable table_user;
    // End of variables declaration//GEN-END:variables
}
